spring.application.name=api-gateway
server.port=8080

services.auth.base-url=http://auth-service/internal/auth
services.measurement.base-url=http://measurement-service/internal/measurements
services.history.base-url=http://history-service/internal/history

app.jwt.secret=AbhayRajputSecurityKeyAbhayRajputSecurityKey

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
